### ISSUE TITLE
Firefox Plugin - NetworkError on Sign in

### ISSUE THREAD

**Issue by nickrallison** [hoarder-app/hoarder#23] opened 2024-03-27 15:30 UTC
When I try to connect to my instance of hoarder on a Tailscale IP and a non standard port, it works on a webpage but doesn't seem to work in a browser extension:

Web page:

![image](https://github.com/MohamedBassem/hoarder-app/assets/99363282/92738f9f-ecd5-4c0a-a668-7353559902b7)

Browser extension:

![image](https://github.com/MohamedBassem/hoarder-app/assets/99363282/ca6dcdf5-8a95-4464-8376-6392a8525dc2)
![image](https://github.com/MohamedBassem/hoarder-app/assets/99363282/c0b43f1c-5301-4f8d-b085-6a2d05bf0401)

**Comment by MohamedBassem** [comment] 2024-03-27 15:32
Can you try prefixing the address with `http://`?

**Comment by vercas** [comment] 2024-03-27 16:24
I'm also getting a `NetworkError`, and my server URL starts with `https://`

**Comment by MohamedBassem** [comment] 2024-03-27 16:45
Hmmm, I wonder if it has something to do with the fact that your SSL certificates are not valid (according to the first screenshot). Is it possible to try disabling SSL and trying again with the `http://` prefix? Just as a test.

**Comment by MohamedBassem** [comment] 2024-03-27 17:27
Perfect!

**Comment by vercas** [comment] 2024-03-27 17:29
I wouldn't close this just yet. I'm not the person who opened the ticket (@nickrallison). Their issue may turn out to be different.

**Comment by MohamedBassem** [comment] 2024-03-27 17:30
Ops, sorry.

**Comment by nickrallison** [comment] 2024-03-27 18:30
I've updated the docker compose stack to the most recently release and changed the url to: http://100.98.101.100:23000/ and am still encountering the original issue

**Comment by MohamedBassem** [comment] 2024-03-27 18:32
Please try removing the trailing slash from the address, this is a bug I fixed but still not released. Sorry, one last try I promise :) 

If you can also capture the error logs from the browser’s console I’d be grateful!

**Comment by nickrallison** [comment] 2024-03-27 21:29
Removing the slash didn't work and the browser console was empty for about a minute after submitting the authentication. 

![image](https://github.com/MohamedBassem/hoarder-app/assets/99363282/9d9cbbdd-5c3e-40dd-9f18-aee593f52f5e)

I printed "Here" right before submitting the log in

The logs from each container also seem empty, the only one with anything interesting was the worker log which only contained job info as far as I can tell

**Comment by MohamedBassem** [comment] 2024-03-27 22:14
Ok, I'm out of ideas for remote debugging :D In chrome, typically, you can open the devtools tab for the "plugin" itself and inspect the network requests the plugin itself is doing.

For example, here's how I debugged the trailing slash bug:

https://github.com/MohamedBassem/hoarder-app/assets/2418637/a82e9cee-2454-4e06-b23e-8d3361eb02e1

I'd expect that if you open the "extension"'s dev tools (not the page's dev tools), you'd find the error in the console logs and you can actually inspect the network request in the network tab. But I don't know how to do this in firefox.

I don't want to waste your time too much. If you're willing to try to repo on chrome and share the error, that would be great. Another option is to share the tailscale node with me temporarily (I can send you my tailscale email), but I'd understand if you don't want to (tbh, I personally wouldn't share my tailscale node with anyone :)). Otherwise, I'm out of ideas on how to help :)

**Comment by nickrallison** [comment] 2024-03-28 15:23
Even more strange, Chrome works right out of the box, firefox still fails. Is it perhaps something strange with my firefox config? I have some strict rules and protections in place: https://github.com/arkenfox/user.js/

**Comment by MohamedBassem** [comment] 2024-03-28 15:27
Oh interesting. Unfortunately, without logs from the plugin's devtool console (or its network tab), it's very hard to figure out why the plugin's requests are failing.

**Comment by nickrallison** [comment] 2024-03-28 15:38
I think I got the relevant logs:
![image](https://github.com/MohamedBassem/hoarder-app/assets/99363282/01dc25a8-f3d8-468c-a57b-33fc6f01ad56)

**Comment by MohamedBassem** [comment] 2024-03-28 15:45
Ok, now we're talking. Are you sure you're on the latest app version? I disabled the CORS policy in v0.10.0 (https://github.com/MohamedBassem/hoarder-app/commit/e6f6873a23dccdc17849f450da3d93838710880c). You being on < 0.10.0 would also explain why it's working on chrome and not in firefox (chrome plugin was explicitly allowlisted. To support firefox, I dropped CORS completely).

If you're using `HOARDER_VERSION=release`, doing a `docker compose up` is not enough to ensure you're on the latest version. You'll need to also do `docker compose up --pull always`. Or instead, pin the version explicitly with `HOARDER_VERSION=0.10.1`.

**Comment by nickrallison** [comment] 2024-03-28 16:08
No dice, I pinned it in my .env file: HOARDER_VERSION=0.10.1

but I'm still getting the same error in the console after a compose down and a compose up. Is there a way in the shell of the container to explicitly check the current version to see if it matches the env var?

**Comment by MohamedBassem** [comment] 2024-03-28 16:25
> Note to self: I should probably add some version number somewhere in the UI itself.

For now, I think one thing that changed in 0.10.0 is that in the worker logs, it used to say:
> Starting openai worker ...

now it says:
> Starting inference worker ...

If you're on >= 0.10.0, you should see the latter.

Also, can you share the output of:

`curl --head https://unraid.vpn:23000/api/trpc/apiKeys.exchange`

This should show the CORS headers of you server.

**Comment by dyslexicjedi** [comment] 2024-03-29 17:59
Same issue as @nickrallison  on latest version 0.10.1

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource ... CORS request did not succeed.

**Comment by MohamedBassem** [comment] 2024-03-29 18:01
Can you share the result of:

```
curl --head <address>/api/trpc/apiKeys.exchange
```
where `<address>` is your full server address?

**Comment by dyslexicjedi** [comment] 2024-03-29 18:03
One thing I did notice was that I said http://ip:port but in the inspect of the extension, I'm seeing https://ip:port. I'm not sure how the http got changed to https in the request. 

```
[rob@turing ~]$ curl --head http://10.0.10.118:3000/api/trpc/apiKeys.exchange
HTTP/1.1 204 No Content
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Credentials: true
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url
Date: Fri, 29 Mar 2024 18:02:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5

[rob@turing ~]$ curl -k --head https://10.0.10.118:3000/api/trpc/apiKeys.exchange
curl: (35) OpenSSL/3.2.1: error:0A0000C6:SSL routines::packet length too long
```

**Comment by MohamedBassem** [comment] 2024-03-29 18:05
> Access-Control-Allow-Origin: *

CORS headers look correct and confirm that you're on at least `10.0.0`. The https thing is interesting. I wonder if you have a `Force HTTPS everywhere` kind of extension that might be causing this?

**Comment by dyslexicjedi** [comment] 2024-03-29 18:07
Yup, on latest.

```
HOARDER_VERSION=release
```

```
rob@hoarder:~$ docker compose pull
WARN[0000] /home/rob/docker-compose.yml: `version` is obsolete 
[+] Pulling 5/5
 ✔ meilisearch Pulled                                                                                                                                         0.5s 
 ✔ web Pulled                                                                                                                                                 0.4s 
 ✔ redis Pulled                                                                                                                                               0.5s 
 ✔ chrome Pulled                                                                                                                                              0.5s 
 ✔ workers Pulled                                                                                                                                             0.4s 
rob@hoarder:~$ docker compose up -d
WARN[0000] /home/rob/docker-compose.yml: `version` is obsolete 
[+] Running 5/5
 ✔ Container rob-meilisearch-1  Started                                                                                                                       0.0s 
 ✔ Container rob-web-1          Started                                                                                                                       0.0s 
 ✔ Container rob-redis-1        Started                                                                                                                       0.0s 
 ✔ Container rob-workers-1      Started                                                                                                                       0.0s 
 ✔ Container rob-chrome-1       Started                                                                                                                       0.0s 
```

**Comment by MohamedBassem** [comment] 2024-03-29 18:08
Yeah, I mean the headers you shared confirm that you're on the latest release. So the culprit is probably something else.

And your `https` thing is a nice observation. Do you have a `force https everywhere` kind of extension?

**Comment by dyslexicjedi** [comment] 2024-03-29 18:24
I've disabled all other extensions and restarted firefox. No change still the same error and still converts from http to https. Could it be some policy inside firefox?

**Comment by MohamedBassem** [comment] 2024-03-29 18:25
It seems that firefox indeed has such a thing:

https://support.mozilla.org/en-US/kb/https-only-prefs

**Comment by dyslexicjedi** [comment] 2024-03-29 18:29
I checked the setting, but it's currently disabled. 

![image](https://github.com/MohamedBassem/hoarder-app/assets/7138525/3963e13a-c7ec-4ace-ac55-e53db5d837f0)

Content-Security-Policy has an alert about upgrading insecure request. Still looking into that "feature"

**Comment by dyslexicjedi** [comment] 2024-03-29 18:37
I'm going to throw a valid cert on that machine and see if it works. That way we can figure out if that really is the problem or not.

**Comment by dyslexicjedi** [comment] 2024-03-29 18:47
I tried it through a reverse proxy with a valid https certificate, same CORS error and dialog error message. I could put a cert directly on the box if you think that would help but I don't think it would make much difference. 

```
rob@hoarder:~$ curl --head https://hoarder.dyslexicjedi.com/api/trpc/apiKeys.exchange
HTTP/1.1 204 No Content
Server: nginx/1.18.0 (Ubuntu)
Date: Fri, 29 Mar 2024 18:46:47 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type, Authorization
Access-Control-Allow-Credentials: true
vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Url

```

**Comment by MohamedBassem** [comment] 2024-03-29 19:34
Is your instance by any chance publicly accessible? Would love to test on my firefox installation.

**Comment by nickrallison** [comment] 2024-03-29 21:50
@dyslexicjedi Do you happen to use the Arkenfox presets for firefox?

**Comment by dyslexicjedi** [comment] 2024-03-29 22:12
@MohamedBassem  No sorry, it's only internal

@nickrallison No, it's Firefox packaged with Arch Linux. No real customization other than a few addons.

**Comment by nickrallison** [comment] 2024-03-29 22:36
I got a temporary instance publicly hosted here: https://hoarder.allisontech.ca/

Strangely it doesn't have the same problem. I suspect it is something to do with my HTTPS I added.

Could I add you to my tailnet perhaps @MohamedBassem? Do you have an email that works?

**Comment by dyslexicjedi** [comment] 2024-03-29 22:44
I'm still getting CORS issues against your public instance.

**Comment by MohamedBassem** [comment] 2024-03-29 22:45
Yeah, it sounds like some weird https issue. I expect that the plugin won't work with an invalid or self-signed cert. On the other hand, @dyslexicjedi tried with a valid cert and faced the same problem :)

Anyways, sent you an email (got yours from your github profile) with my tailscale email :)

**Comment by MohamedBassem** [comment] 2024-03-29 22:46
@dyslexicjedi Any chance it's a different CORS issue? For example, are you by any chance adding a trailing slash to the URL? :) This causes a CORS issue but a different one. A one that I already fixed in the extension version 1.1.1 :)

I'm not getting any CORS issues in the public instance on firefox.

**Comment by dyslexicjedi** [comment] 2024-03-29 22:53
So I was messing around with my nginx reverse proxy and CORS..... and I got it to work. 

My config:
```
server {
  listen 0.0.0.0:443 ssl;
  server_name hoarder.dyslexicjedi.com;

  include ssl.conf;

  location / {
    if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Con>
      add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      add_header 'Content-Length' 0;
      return 204;
    }
    proxy_pass http://10.0.10.118:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  }
}
```

**Comment by MohamedBassem** [comment] 2024-03-29 23:14
I managed to repro the issue on @nickrallison's private instance (over tailscale). Basically CORS is failing because SSL is failing with `SSL_ERROR_RX_RECORD_TOO_LONG`. This error means we're trying to talk SSL over an HTTP only port.

<img width="1323" alt="Screenshot 2024-03-29 at 11 10 42 PM" src="https://github.com/MohamedBassem/hoarder-app/assets/2418637/c14c4c6d-c3da-4b94-b056-20c08af5efe6">

You can repro this error by opening the `https://100.98.101.100:23000/signin` in a tab. (Notice that https is the protocol which is talking directly to hoarder's port). So it's definitely an SSL/HTTPs issue and using a valid certificate should solve this issue.

Now, the question remains. Why tf is firefox forcing an upgrade to https :)

**Comment by dyslexicjedi** [comment] 2024-03-29 23:17
Yes, valid cert with no trailing slash was still failing. Only the nginx hack fixed it, but then again based on what you said previously. Firefox is communicating over a valid SSL cert to nginx and nginx is communicating over standard http to hoarder. so it's possible that nginx is solving the firefox SSL upgrade problem somehow. (not sure that made sense, but it kinda does in my head.)

**Comment by MohamedBassem** [comment] 2024-03-30 00:18
Ok, I have a minimal repro that's irrelevant to `Hoarder` server.

- Start a local python server with `python3 -m http.server 8000`
- Get your local lan IP
- In the extension, use `http://<local_lan_ip>:8000` as the server address
- Use any username and password.
- You'll get the same CORS error we've been debugging, and the python server will receive some SSL garbage.

Notice, that if you use `localhost` or `127.0.0.1`, firefox won't upgrade the request to https.

It seems that firefox addons upgrades ANY http request to https regardless of the website. I don't know why this is happening to be honest. The next suspect would be maybe something in the plugin code itself? I'll check.

**Comment by nickrallison** [comment] 2024-03-30 19:36
I got it working, it was not the fix i would like but I forwarded my domain to a second local Nginx instance on a VM so not publically. After adding https it works like it's meant to. Thanks for all the support

**Comment by nickrallison** [comment] 2024-03-30 19:58
Perhaps another band aid would be a disclaimer to firefox users and the advice to host it publicly and disable sign ups once issue #52 gets resolved

**Comment by MohamedBassem** [comment] 2024-03-30 20:03
You don't actually need to host it publicly. You just need to have a valid certificate. You can get valid certs for non public domains with DNS challenge in Lets Encrypt. Most of my homelab is non-public (hosted on tailscale) and has valid certs.

**Comment by alejoar** [comment] 2024-04-06 11:31
I'm facing this same issue (confirmed looking at the extension console logs) and hosting through cosmos with a custom domain. The site is publicly accessible with https. 

Any tips on how to fix it with this setup?

**Comment by MohamedBassem** [comment] 2024-04-06 11:34
@alejoar if you're using cosmos, you might want to check the custom CORS header configuration. Check https://github.com/MohamedBassem/hoarder-app/issues/51 for details on how we debug a previous instance with cosmos.

**Comment by alejoar** [comment] 2024-04-06 11:43
@MohamedBassem amazing, that worked, thank you!

**Comment by lucius346346** [comment] 2024-04-19 06:35
Is there any plan for fixing this? Setting up SSL for just that would be a hassle?

**Comment by MohamedBassem** [comment] 2024-04-19 09:54
@lucius346346 to be honest, I'm not entirely sure if this something that can be "fixed" or if it's a firefox restriction that can't be bypassed. So far, I didn't find any reference online stating this requirement and I'm not entirely sure what needs to be fixed.

**Comment by axsddlr** [comment] 2024-04-27 16:13
having same issue on both chrome, edge, waterfox and firefox

**Comment by MohamedBassem** [comment] 2024-05-25 18:35
@kamtschatka this is a great find! I didn't know that firefox adds `upgrade-insecure-requests` to CSP, and it's not even documented in their docs!

Regarding the local build, `pnpm run dev` doesn't seem to work with firefox, but `pnpm run build` does work. You need to follow [this link](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing) to install the extenion.

**Closed** 2024-05-25 18:41 UTC

**Comment by MohamedBassem** [comment] 2024-05-25 19:16
I've just released v1.2.1 to the mozilla store with @kamtschatka. If anyone was facing this problem, please give it a shot and let us know how it goes.
Once again, thanks a ton @kamtschatka for tracking and fixing this long standing problem!

**Comment by MRDGH2821** [comment] 2024-08-05 11:30
I'm having trouble getting the extension working unfortunately.

I am using Cosmos Cloud to manage my services, but for Hoarder, I directly used compose files to launch instead of adding it in Cosmos Cloud then launching.

After that I added subdomain, put `*` in CORS policy setting of Cosmos, disabled `HTTPS-only` setting of firefox, but can't get it working.

![image](https://github.com/user-attachments/assets/460bcf4f-53f1-491f-9160-91ed34c9f88f)

The app works without a problem.

This is command output from server:
![image](https://github.com/user-attachments/assets/450a815d-619a-4635-bb88-936297af64e7)

And this is command output from WSL2 (I don't have any other linux device)
![image](https://github.com/user-attachments/assets/8a1e7b97-a2cd-4fec-be74-5f9f922bb714)

That one thing which is bothering me is duplicate headers.

Hoarder Version: 0.15.0
App version 1.6.0
Extension Version: 1.2.1

**Comment by MRDGH2821** [comment] 2024-08-05 11:34
> I'm having trouble getting the extension working unfortunately.
> 
> I am using Cosmos Cloud to manage my services, but for Hoarder, I directly used compose files to launch instead of adding it in Cosmos Cloud then launching.
> 
> After that I added subdomain, put `*` in CORS policy setting of Cosmos, disabled `HTTPS-only` setting of firefox, but can't get it working.
> 
> ![image](https://private-user-images.githubusercontent.com/46621001/355083374-460bcf4f-53f1-491f-9160-91ed34c9f88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTc3MjYsIm5iZiI6MTcyMjg1NzQyNiwicGF0aCI6Ii80NjYyMTAwMS8zNTUwODMzNzQtNDYwYmNmNGYtNTNmMS00OTFmLTkxNjAtOTFlZDM0YzlmODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzkwODkyY2ViNGY1ZjA2NWNmNTI5ZmY3YjZjNWU1NjUyNGQxZDEyMmI5YjE1Yzk1NDU3YTkyMzYxZDA4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ln-AItMEljl_0tONrvi2F0cjz7zmtxwZsOE0rzoxJ5Q)
> 
> The app works without a problem.
> 
> This is command output from server: ![image](https://private-user-images.githubusercontent.com/46621001/355084682-450a815d-619a-4635-bb88-936297af64e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTc3MjYsIm5iZiI6MTcyMjg1NzQyNiwicGF0aCI6Ii80NjYyMTAwMS8zNTUwODQ2ODItNDUwYTgxNWQtNjE5YS00NjM1LWJiODgtOTM2Mjk3YWY2NGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1MjIwZTY0Zjg3N2Y0OTgxNzVlMTMzYTA5OTUxNmY1OGU4ZjVlZTU4YzU0ZWY2ZTJjYzIzYmM4M2M2MzcxZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QpOS_o93wgUISPq6g7yI6vBdperbgjg1lv4sJFrVUA0)
> 
> And this is command output from WSL2 (I don't have any other linux device) ![image](https://private-user-images.githubusercontent.com/46621001/355084973-8a1e7b97-a2cd-4fec-be74-5f9f922bb714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTc3MjYsIm5iZiI6MTcyMjg1NzQyNiwicGF0aCI6Ii80NjYyMTAwMS8zNTUwODQ5NzMtOGExZTdiOTctYTJjZC00ZmVjLWJlNzQtNWY5ZjkyMmJiNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNDljM2ZlYTU5NmFkNmYzZjQyNzZlYTVhMDA4YTcwMzg5YTg1NTUwNmE4ZTY3N2MwYTI5NGQyZjZiZDU0ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xbOYJHtM3RU8yLMJaWo84ZfwvBk5eWt_P45jRLkG9-Q)
> 
> That one thing which is bothering me is duplicate headers.
> 
> Hoarder Version: 0.15.0 App version 1.6.0 Extension Version: 1.2.1

I found the problem!
I had duplicate urls in Cosmos cloud, Removed the duplicate & it worked.

I had renamed the container names in docker compose so I had to recreate a URL, didn't know cosmos would keep the previous URL settings too.
