### ISSUE TITLE
Feature request: Add tags to iOS app

### ISSUE THREAD

**Issue by marnas** [hoarder-app/hoarder#619] opened 2024-11-06 09:08 UTC
### Describe the feature you'd like

I couldn't find a way to add or manage tags for bookmars from the iOS app, I think it would be a very nice addition.

### Describe the benefits this would bring to existing Hoarder users

I think tags are a great way to keep your bookmarks organised, I usually try to add at least a few for each new bookmark that I add.
It would be nice to be able to do that from the mobile as well, since that's the place where I ofted add new bookmarks that I will later on check from my PC.

### Can the goal of this request already be achieved via other means?

No

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by Inventhrice** [comment] 2024-11-07 03:40
+1 This is an issue that applies for all mobile applications, including Android

**Comment by Inventhrice** [comment] 2024-11-07 03:46
is this perhaps a duplicate of #317?

**Comment by MohamedBassem** [comment] 2024-11-09 11:47
Yeah, this is kinda a duplicate of #317 which is already in our roadmap. Let's track the work there.

**Closed by MohamedBassem** 2024-11-09 11:47 UTC
Labels: feature request, ios
