### ISSUE TITLE
Can't commit changes due to ESLint errors

### ISSUE THREAD

**Issue by lilacpixel** [hoarder-app/hoarder#151] opened 2024-05-12 23:31 UTC
I have a couple more changes I'd love to submit as PRs, but out of the blue, I'm getting errors from the linter on files that I didn't touch:

```
@hoarder/web:lint: Error while loading rule '@typescript-eslint/no-unused-vars': (0 , eslint_utils_1.getFilename) is not a function
@hoarder/web:lint: Occurred while linting /Users/cari/Projects/hoarder-app/apps/web/app/api/assets/[assetId]/route.ts
@hoarder/web:lint:  ELIFECYCLE  Command failed with exit code 1.
@hoarder/web:lint: command finished with error, but continuing...
@hoarder/web#lint: command (/Users/cari/Projects/hoarder-app/apps/web) /opt/homebrew/bin/pnpm run lint --cache --cache-location node_modules/.cache/.eslintcache exited (1)

 Tasks:    10 successful, 11 total
Cached:    10 cached, 11 total
  Time:    3.085s
Failed:    @hoarder/web#lint

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

Blowing away the entire project folder, cloning the repo again, and putting all of my changes back worked once, but now it's back and I'm stuck.

Any suggestions? I'm not sure what might be happening, since, ostensibly, no one else is having trouble with this file. Hoping someone else might have an idea!

**Comment by MohamedBassem** [comment] 2024-05-13 07:05
can you try going inside 'apps/web' and running 'pnpm lint' manually to see if the problem still appears?

if it does, maybe try 'pnpm clean' & 'pnpm clean:workspaces' in the root of the repo to nuke all the caches and start again?

**Comment by lilacpixel** [comment] 2024-05-13 14:56
Thanks, `--no-verify` got me going again! Looks like everything checks out in GitHub Actions, which at least confirms that it's something wonky in my environment…

When I wipe out the caches and start over with `pnpm install`, pnpm v9.1.1 goes through and upgrades a bunch of packages, including a bunch of ESLint ones:

```
   tooling/eslint:
     dependencies:
       '@next/eslint-plugin-next':
         specifier: ^14.1.1
-        version: 14.1.1
+        version: 14.2.3
       '@typescript-eslint/eslint-plugin':
         specifier: 7.6.0
-        version: 7.6.0(@typescript-eslint/parser@7.6.0(eslint@8.57.0)(typescript@5.3.3))(eslint@8.57.0)(typescript@5.3.3)
+        version: 7.6.0(@typescript-eslint/parser@7.6.0(eslint@8.57.0)(typescript@5.4.5))(eslint@8.57.0)(typescript@5.4.5)
       '@typescript-eslint/parser':
         specifier: 7.6.0
-        version: 7.6.0(eslint@8.57.0)(typescript@5.3.3)
+        version: 7.6.0(eslint@8.57.0)(typescript@5.4.5)
       eslint-config-turbo:
         specifier: ^1.12.4
-        version: 1.12.5(eslint@8.57.0)
+        version: 1.13.3(eslint@8.57.0)
       eslint-plugin-import:
         specifier: ^2.29.1
-        version: 2.29.1(@typescript-eslint/parser@7.6.0(eslint@8.57.0)(typescript@5.3.3))(eslint@8.57.0)
+        version: 2.29.1(@typescript-eslint/parser@7.6.0(eslint@8.57.0)(typescript@5.4.5))(eslint@8.57.0)
       eslint-plugin-jsx-a11y:
         specifier: ^6.8.0
         version: 6.8.0(eslint@8.57.0)
       eslint-plugin-react:
         specifier: ^7.33.2
-        version: 7.33.2(eslint@8.57.0)
+        version: 7.34.1(eslint@8.57.0)
       eslint-plugin-react-hooks:
         specifier: ^4.6.0
-        version: 4.6.0(eslint@8.57.0)
+        version: 4.6.2(eslint@8.57.0)
     devDependencies:
       '@hoarder/prettier-config':
         specifier: workspace:^0.1.0
@@ -962,7 +962,7 @@ importers:
         version: link:../typescript
       '@types/eslint':
         specifier: ^8.56.5
-        version: 8.56.5
+        version: 8.56.10
       eslint:
         specifier: ^8.57.0
         version: 8.57.0
@@ -971,7 +971,7 @@ importers:
         version: 3.2.5
       typescript:
         specifier: ^5.3.3
-        version: 5.3.3
+        version: 5.4.5
```

I can only guess that's where things are going wrong for me, but I'm not sure what to do about it, short of just sticking with `--no-verify` and letting GitHub tell me when I break something 😜 Unfortunately, running the v9.0.0-alpha.8 version of pnpm doesn't work at all on my machine--it fails with a different set of errors during the initial setup phase. Are there specific ESLint packages I might be able to pin to keep the errors in check? I'm honestly wondering now how my first PR went through without getting caught up in this…

**Comment by MohamedBassem** [comment] 2024-07-01 11:46
I'll close this for now, and tackle it when we start ugprading pnpm and the dependencies

**Closed by MohamedBassem** 2024-07-01 11:46 UTC

**Comment by digithree** [comment] 2025-05-31 09:52
I'm having a similar issue, it is with the `pnpm format --check` check configured with Husky, the others work fine.

```
> karakeep@0.1.0 format ***/karakeep-app/karakeep
> turbo --no-daemon format --continue -- --cache-location node_modules/.cache/.prettiercache "--check"

turbo 2.1.2

• Packages in scope: @karakeep/api, @karakeep/cli, @karakeep/db, @karakeep/docs, @karakeep/e2e_tests, @karakeep/eslint-config, @karakeep/github, @karakeep/landing, @karakeep/mcp, @karakeep/mobile, @karakeep/open-api, @karakeep/prettier-config, @karakeep/sdk, @karakeep/shared, @karakeep/shared-react, @karakeep/tailwind-config, @karakeep/trpc, @karakeep/tsconfig, @karakeep/web, @karakeep/workers, browser-extension
• Running format in 21 packages
• Remote caching disabled
@karakeep/web:format: cache miss, executing ec678de539f822a8
@karakeep/shared:format: cache hit, suppressing logs 6291fa17b0597098
@karakeep/eslint-config:format: cache hit, suppressing logs 7ec308986f7300d1
@karakeep/web:format: 
@karakeep/e2e_tests:format: cache hit, suppressing logs c807aa2ae8ce0077
@karakeep/mobile:format: cache hit, suppressing logs eff23d112cc95059
@karakeep/open-api:format: cache hit, suppressing logs 10e8bda3b2591bb9
@karakeep/cli:format: cache hit, suppressing logs 0d2fb378cf8fbe17
@karakeep/mcp:format: cache hit, suppressing logs f8d0f86a282e66ef
@karakeep/tailwind-config:format: cache hit, suppressing logs df6bd641e12a6341
@karakeep/prettier-config:format: cache hit, suppressing logs c688286df9c7acdc
@karakeep/api:format: cache hit, suppressing logs 02ab9ae479f74289
@karakeep/trpc:format: cache hit, suppressing logs 1427e20e06bf1d28
@karakeep/sdk:format: cache hit, suppressing logs 6cfb6350a8be0a83
@karakeep/shared-react:format: cache hit, suppressing logs 30daff2bf022fa21
@karakeep/landing:format: cache hit, suppressing logs 529b558398b96b20
browser-extension:format: cache miss, executing 24d43a0407d23270
browser-extension:format: 
@karakeep/workers:format: cache hit, suppressing logs 20fd9d9e70b62b2e
@karakeep/web:format: 
@karakeep/web:format: > @karakeep/web@0.1.0 format ***/karakeep-app/karakeep/apps/web
@karakeep/web:format: > prettier --check . --ignore-path ../../.gitignore "--cache-location" "node_modules/.cache/.prettiercache" "--check"
@karakeep/web:format: 
browser-extension:format: 
browser-extension:format: > browser-extension@0.0.0 format ***/karakeep-app/karakeep/apps/browser-extension
browser-extension:format: > prettier . "--cache-location" "node_modules/.cache/.prettiercache" "--check"
browser-extension:format: 
@karakeep/web:format: Checking formatting...
browser-extension:format: Checking formatting...
(node:89136) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
browser-extension:format: (Use `node --trace-warnings ...` to show where the warning was created)
(node:89114) ExperimentalWarning: Type Stripping is an experimental feature and might change at any time
@karakeep/web:format: (Use `node --trace-warnings ...` to show where the warning was created)
[warn] src/components/ui/dialog.tsx
[warn] src/components/ui/popover.tsx
[warn] Code style issues found in 2 files. Run Prettier with --write to fix.
browser-extension:format:  ELIFECYCLE  Command failed with exit code 1.
browser-extension:format: command finished with error, but continuing...
[warn] components/dashboard/highlights/HighlightCard.tsx
[warn] components/dashboard/preview/LinkContentSection.tsx
[warn] components/ui/dialog.tsx
[warn] components/ui/dropdown-menu.tsx
[warn] components/ui/markdown/markdown-editor.tsx
[warn] components/ui/popover.tsx
[warn] components/ui/select.tsx
[warn] components/ui/toast.tsx
[warn] components/ui/tooltip.tsx
[warn] Code style issues found in 9 files. Run Prettier with --write to fix.
@karakeep/web:format:  ELIFECYCLE  Command failed with exit code 1.
@karakeep/web:format: command finished with error, but continuing...
browser-extension#format: command (***/karakeep-app/karakeep/apps/browser-extension) /opt/homebrew/bin/pnpm run format --cache-location node_modules/.cache/.prettiercache --check exited (1)
@karakeep/web#format: command (***/karakeep-app/karakeep/apps/web) /opt/homebrew/bin/pnpm run format --cache-location node_modules/.cache/.prettiercache --check exited (1)

 Tasks:    15 successful, 17 total
Cached:    15 cached, 17 total
  Time:    2.67s 
Failed:    @karakeep/web#format, browser-extension#format

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
```

(I've just replaced my local path with `***`)

Environment is an M1 Mac on 15.5

**Comment by MohamedBassem** [comment] 2025-05-31 09:54
@digithree It's failing the formatting check. You can fix it with `pnpm format:fix && pnpm lint:fix` and then commit. If you want to skip the prechecks altogether you can pass `-n` (e.g. `git commit -n -m "message"`)

**Comment by digithree** [comment] 2025-05-31 09:58
Thanks for the reply @MohamedBassem 

I had just assumed that contributing developers would have come across this when committing due to the Husky config if this were legit, can you reproduce locally from latest on `main`? I'm happy to fix but would have thought `main` would be green by all checks always

**Comment by digithree** [comment] 2025-05-31 10:00
@MohamedBassem I have to apologise, I rubber-ducked myself here, I realised I was on Node 20, not 22! After upgrading it does not reproduce
