### ISSUE TITLE
Edit links post hoarding

### ISSUE THREAD

**Issue by raviwarrier** [hoarder-app/hoarder#634] opened 2024-11-10 03:51 UTC
### Describe the feature you'd like

It would be nice to be able to edit the links of the hoarded bookmarks.

![image](https://github.com/user-attachments/assets/edd8e662-546c-426b-83c3-102506926acf)

This could be a manual way to clean up URLS (like I mentioned in my previous feature request) 

### Describe the benefits this would bring to existing Hoarder users

Allows a little more flexibility in managing their bookmarks.

### Can the goal of this request already be achieved via other means?

Not really.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by kamtschatka** [comment] 2024-11-10 07:05
duplicate of https://github.com/hoarder-app/hoarder/issues/375

**Closed by kamtschatka** 2024-11-10 07:05 UTC
