### ISSUE TITLE
[Feature request] Add the ability to tag on the Android app.

### ISSUE THREAD

**Issue by nicktheone** [hoarder-app/hoarder#519] opened 2024-10-08 21:05 UTC
As far as I can see it's not possible right now and I'd like to request it as a feature because I'd love to be able to tag stuff directly from the Android app.

**Comment by kamtschatka** [comment] 2024-10-09 05:52
duplicate of https://github.com/hoarder-app/hoarder/issues/317

**Closed by kamtschatka** 2024-10-09 05:52 UTC
Labels: feature request, ios, android
