### ISSUE TITLE
Allow AI to only use tags created by the user

### ISSUE THREAD

**Issue by devbydaniel** [hoarder-app/hoarder#529] opened 2024-10-13 12:19 UTC
Hi! First of all, great app! 

I was wondering if you'd consider an option where users can restrict the automatic AI tagging to only use tags which are created by the user.

The background is that some people (like me) will have a pretty clear set of pre-defined tags which they want to use. Restricting the AI to only use these tags would greatly improve the organization of the bookmark library because everything will be sorted into expected buckets. 

I briefly went through your code, and I think the implementation could look something like
- extend the prompt builder functions in `/packages/shared/prompts.ts` to accept an optional `userDefinedTags` param and if present, add those tags to the prompt
- If the results are unreliable, switch the OpenAI call to use [function calling](https://platform.openai.com/docs/guides/function-calling) as the way to return the list of tags (since launching the [structured output API extension](https://openai.com/index/introducing-structured-outputs-in-the-api/), OpenAI guarantees 100% accuracy in function calling, so this should definitely work), e.g. like so:
```ts
{
    "name": "assign_tags",
    "description": "Assign tags to the given bookmark according to the content. If no tags fit the bookmark, return an empty array",
    "parameters": {
        "type": "object",
        "properties": {
            "tags": {
                "type": "array",
                "description": "The array of tags which should be assigned to the bookmark.",
                "items": {
                    "type": "string",
                    "enum": ["tag1", "tag2", "tag3"] // dynamically load user tags here
                },
            },
        },
        "required": ["tags"],
        "additionalProperties": false,
    }
}
```
- add an option to the UI to restrict tag assignment to only consider user defined tags
- in `/apps/workers/openaiWorker.ts` check if that option is present and if so, pass the user defined tags to the prompt builder

I'm happy to support you / provide more details / try to implement it myself as soon as I have time in case that sounds interesting for you.

**Comment by kamtschatka** [comment] 2024-10-13 12:49
Sounds exactly like https://github.com/hoarder-app/hoarder/issues/111, but with some suggestions on how to fix it?

**Comment by devbydaniel** [comment] 2024-10-13 14:40
Ahh, thanks for the hint, I will respond there

**Comment by kamtschatka** [comment] 2024-10-13 15:44
duplicate of https://github.com/hoarder-app/hoarder/issues/111

**Closed by kamtschatka** 2024-10-13 15:44 UTC
