### ISSUE TITLE
Crawl / store pages that are behind a login

### ISSUE THREAD

**Issue by Ronaldvr** [hoarder-app/hoarder#607] opened 2024-10-31 23:06 UTC
### Describe the feature you'd like

It seems possible if I search the web: I have several pages that are behind a login, and these cannot be crawled without providing the necessary credentials.

### Describe the benefits this would bring to existing Hoarder users

You can store and keep the content even when you login expires, lapses, or the site itself stops

### Can the goal of this request already be achieved via other means?

Perhaps: The previously mentioned SingleFile can be used, but then hoarder has to support those html files as input.

### Have you searched for an existing open/closed issue?

- [X] I have searched for existing issues and none cover my fundamental request

**Comment by MohamedBassem** [comment] 2024-11-01 00:02
Duplicate of #172

**Closed by MohamedBassem** 2024-11-01 00:02 UTC
